service: colonial-electrical-supply-calci
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
      - Effect: Allow
        Action: 
          - ses:*
          - s3:*
        Resource: '*'
 
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
